### ISSUE TITLE
LifecycleException: Could not stop container caused by java.lang.IllegalStateException: The client connection has been closed.

### ISSUE THREAD

**Issue by dudaerich** [wildfly/wildfly-arquillian#102]
Hi,
in our test suite we use 4 wildfly containers which are during the test stopped, started, restarted. Sometimes following exception is thrown from the `ClientContainerController.stop` method.

```
org.jboss.arquillian.container.spi.client.container.LifecycleException: Could not stop container
        at org.jboss.as.arquillian.container.managed.ManagedDeployableContainer.stopInternal(ManagedDeployableContainer.java:296)
        at org.jboss.as.arquillian.container.CommonDeployableContainer.stop(CommonDeployableContainer.java:127)
        at org.jboss.arquillian.container.impl.ContainerImpl.stop(ContainerImpl.java:217)
        at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$9.perform(ContainerLifecycleController.java:178)
        at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$9.perform(ContainerLifecycleController.java:172)
        at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forContainer(ContainerLifecycleController.java:255)
        at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.stopContainer(ContainerLifecycleController.java:171)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
        at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:57)
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
        at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
        at org.jboss.arquillian.container.test.impl.client.container.ClientContainerController.stop(ClientContainerController.java:204)
        at org.jboss.qa.hornetq.ContainerEAP7.stop(ContainerEAP7.java:305)
        at org.jboss.qa.hornetq.ContainerEAP7.stop(ContainerEAP7.java:254)
        at org.jboss.qa.hornetq.test.prepares.generic.FourNodes.prepareMethod(FourNodes.java:98)
        at org.jboss.qa.hornetq.test.prepares.generic.RemoteJCA.prepareMethod(RemoteJCA.java:27)
        ... 63 more
Caused by: java.lang.IllegalStateException: The client connection has been closed.
        at org.jboss.as.arquillian.container.ManagementClient.checkState(ManagementClient.java:481)
        at org.jboss.as.arquillian.container.ManagementClient.getControllerClient(ManagementClient.java:137)
        at org.jboss.as.arquillian.container.managed.ManagedDeployableContainer.stopInternal(ManagedDeployableContainer.java:285)
        ... 90 more
```

I debugged why this is happening. I found out that `managementClient.get()` doesn't return always the same instance as it was created in `start` method.

When I looked at implementation of `InstanceImpl` in Arquillian core, I noticed one thing.

```
public void set(T value)
   {
      if(scope == null)
      {
         throw new IllegalStateException("Value can not be set, instance has no Scope defined: " + value);
      }
      manager.bindAndFire(scope, type, value);
   }
```
The set method doesn't associate `CommonDeployableContainer` instance with `ManagementClient` instance. The association is done only on type level. So anytime you call managementClient.get() you will get random instance of ManagementClient.

So in my case `CommonDeployableContainer` wants to close `ManagementClient` instance which was already closed by another `CommonDeployableContainer`.

**Comment by ctomc** [comment]
Yes instance of managementClient changes every time you restart/reload server, that is proper behavior.

What version of wildfly-arquillian container do you use?

**Comment by dudaerich** [comment]
I agree that managementClient can change between restarts but in my case it was changed between calling of methods `CommonDeployableContainer.stopInternal` and `CommonDeployableContainer.safeCloseClient`. I debugged it using a Byteman.

I use a version `2.0.0.Final` but I already tried with `2.0.2.Final`. I saw the same issue.

**Comment by dudaerich** [comment]
I'm attaching byteman rules which I used for debugging.

```
RULE trace init management client
CLASS org.jboss.as.arquillian.container.ManagementClient
METHOD <init>
AT ENTRY
IF true
DO traceStack("BYTEMAN DEBUG - INIT CLIENT " + $0 + "\n", 1000)
ENDRULE

RULE trace close management client
CLASS org.jboss.as.arquillian.container.ManagementClient
METHOD close
AT ENTRY
IF true
DO traceStack("BYTEMAN DEBUG - CLOSE CLIENT " + $0 + "\n", 1000)
ENDRULE

RULE trace close
CLASS org.jboss.as.arquillian.container.CommonDeployableContainer
METHOD safeCloseClient
AT ENTRY
IF true
DO traceStack("BYTEMAN DEBUG - CLOSE " + $0 + " managementClient: " + $0.managementClient + "-" + $0.getManagementClient() + "\n", 1000)
ENDRULE

RULE stopping container entry
CLASS org.jboss.as.arquillian.container.CommonDeployableContainer
METHOD stop
AT ENTRY
IF true
DO traceStack("BYTEMAN DEBUG - STOP ENTRY" + $0 + " managementClient: " + $0.managementClient + "-" + $0.getManagementClient() + "\n", 1000)
ENDRULE

RULE stopping container exit
CLASS org.jboss.as.arquillian.container.CommonDeployableContainer
METHOD stop
AT EXIT
IF true
DO traceStack("BYTEMAN DEBUG - STOP EXIT" + $0 + " managementClient: " + $0.managementClient + "-" + $0.getManagementClient() + "\n", 1000)
ENDRULE

RULE at throwing exception at stop
CLASS org.jboss.as.arquillian.container.CommonDeployableContainer
METHOD stop
AT THROW ALL
IF true
DO traceStack("BYTEMAN DEBUG - THROW STOP " + $0 + " managementClient: " + $0.managementClient + "-" + $0.getManagementClient() + "\n", 1000)
ENDRULE

RULE starting container
CLASS org.jboss.as.arquillian.container.CommonDeployableContainer
METHOD start
AT EXIT
IF true
DO traceStack("BYTEMAN DEBUG - START " + $0 + " managementClient: " + $0.managementClient + "-" + $0.getManagementClient() + "\n", 1000)
ENDRULE

RULE at throwing exception at start
CLASS org.jboss.as.arquillian.container.CommonDeployableContainer
METHOD start
AT THROW ALL
IF true
DO traceStack("BYTEMAN DEBUG - THROW START " + $0 + " managementClient: " + $0.managementClient + "-" + $0.getManagementClient() + "\n", 1000)
ENDRULE

RULE injection point
CLASS InjectionPointImpl
METHOD set
AT ENTRY
BIND runnableKlazz = $0.target.getClass().getName()
IF runnableKlazz.equals("org.jboss.as.arquillian.container.managed.ManagedDeployableContainer")
DO traceStack("BYTEMAN DEBUG - INJECTION container: " + $0.target + " injection: " + $1 + "\n")
ENDRULE

RULE setting instance
CLASS org.jboss.arquillian.core.impl.InstanceImpl
METHOD set
AT ENTRY
BIND runnableKlazz = $1.getClass().getName()
IF runnableKlazz.equals("org.jboss.as.arquillian.container.ManagementClient")
DO traceStack("BYTEMAN DEBUG - SET: " + $1 + "\n")
ENDRULE
```

**Comment by dudaerich** [comment]
And I forgot to mention that ClientContainerControllers are used from different threads. We start, stop and restart containers in parallel. Each thread manages one container.

**Comment by jamezp** [comment]
This should work once https://issues.jboss.org/browse/WFARQ-11 is resolved. It should already work for domains, but IIRC I had some issues with standalone. It should be doable though and it looks like I have a branch locally with some of the changes.

**Comment by ctomc** [comment]
wildfly-arquillian containers ware never meant to be running in multiple threads like this.

You should start and stop all containers (serialized), what you do between that can be as multi threaded as possible.

**Comment by dudaerich** [comment]
Thanks both for response.
Our use case is configuration of several Wildfly containers in parallel what significantly shorts time of test execution.

@jamezp I am glad to hear that you already did some work on this. It would be perfect if you finish it and thereby fix issue in our use case.

**Comment by jamezp** [comment]
It should be done soon. I've got it mostly done locally. It's built on top of some pending PR's though so I need to get those merged first. That said I'm going to go ahead and close this. Feel free to follow the JIRA though.
