### ISSUE TITLE
java.lang.OutOfMemoryError: PermGen space problem while deploying.

### ISSUE THREAD

**Issue by kytay** [wildfly/wildfly-arquillian#33]
Hi 

I have come across some problems when trying to test using wildfly-embedded. From some search results, the possible resolution is to setup -XX:MaxPermSize, but unfortunately I cannot pass any jvm args while creating the arquillian container. 

Is there a way to work around this?

> ERROR [org.jboss.msc.service.fail] MSC000001: Failed to start service jboss.deployment.subunit."f71ddb2d-bfa8-407a-8670-5f27a230a29b.ear"."82d2f032-e802-40ab-805a-c54da70352fe.jar".component.Service.START: org.jboss.msc.service.StartException in service jboss.deployment.subunit."f71ddb2d-bfa8-407a-8670-5f27a230a29b.ear"."82d2f032-e802-40ab-805a-c54da70352fe.jar".component.Service.START: java.lang.OutOfMemoryError: PermGen space
	at org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [rt.jar:1.7.0_80]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]
	at org.jboss.threads.JBossThread.run(JBossThread.java:122) [jboss-threads-2.1.1.Final.jar:2.1.1.Final]
> Caused by: java.lang.OutOfMemoryError: PermGen space

Maven
```
<profile>
			<id>wildfly821-embedded</id>
			<!-- the dependencies for Wildfly8.1 -->
			<dependencies>
				<dependency>
					<groupId>org.wildfly</groupId>
					<artifactId>wildfly-arquillian-container-embedded</artifactId>
					<version>8.2.1.Final</version>
				</dependency>
				<dependency>
					<groupId>org.wildfly</groupId>
					<artifactId>wildfly-embedded</artifactId>
					<version>8.2.1.Final</version>
				</dependency>
			</dependencies>

			<build>
				<plugins>
					<!-- You need the maven dependency plugin to download locally a zip 
						with the server, unless you provide your own, it will download under the 
						/target directory -->
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-dependency-plugin</artifactId>
						<version>2.10</version>
						<executions>
							<execution>
								<id>unpack</id>
								<phase>process-test-classes</phase>
								<goals>
									<goal>unpack</goal>
								</goals>
								<configuration>
									<artifactItems>
										<artifactItem>
											<groupId>org.wildfly</groupId>
											<artifactId>wildfly-dist</artifactId>
											<version>8.2.1.Final</version>
											<type>zip</type>
											<overWrite>false</overWrite>
											<outputDirectory>target</outputDirectory>
										</artifactItem>
									</artifactItems>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<version>2.17</version>
						<configuration>
							<!-- Fork every test because it will launch a separate AS instance -->
							<forkMode>always</forkMode>
							<systemPropertyVariables>
								<arquillian.launch>wildflyContainer</arquillian.launch>
								<java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
								<!-- the maven dependency plugin will have already downloaded the server on /target -->
								<jboss.home>${project.basedir}/target/wildfly-8.2.1.Final</jboss.home>
								<module.path>${project.basedir}/target/wildfly-8.2.1.Final/modules</module.path>
							</systemPropertyVariables>
							<redirectTestOutputToFile>false</redirectTestOutputToFile>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
```

**Comment by kytay** [comment]
Found something. Hope it is useful.

Add 
<argLine>-Xms128m -Xmx512m -XX:MaxPermSize=1024m</argLine>
to sunfire-plugin to set the jvm configuration

```
<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<version>2.17</version>
						<configuration>
							<argLine>-Xms128m -Xmx512m -XX:MaxPermSize=1024m</argLine>
							<!-- Fork every test because it will launch a separate AS instance -->
							<forkMode>always</forkMode>
							<systemPropertyVariables>
								<arquillian.launch>wildflyContainer</arquillian.launch>
								<java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
								<!-- the maven dependency plugin will have already downloaded the server on /target -->
								<jboss.home>${project.basedir}/target/wildfly-8.2.1.Final</jboss.home>
								<module.path>${project.basedir}/target/wildfly-8.2.1.Final/modules</module.path>
							</systemPropertyVariables>
							<redirectTestOutputToFile>false</redirectTestOutputToFile>
						</configuration>
					</plugin>
```
