### ISSUE TITLE
Can not run arquillian tests on wildfly-10.x

### ISSUE THREAD

**Issue by Afarzin** [wildfly/wildfly-arquillian#71]
After upgrading to wildfly 10 I couldn't run my arquillian tests on the target server.
The error it shows is:
`Exception in thread "Remoting "management-client" task-4" java.lang.NoSuchMethodError: org.jboss.as.protocol.mgmt.ManagementRequestContext.executeAsync(Lorg/jboss/as/protocol/mgmt/ManagementRequestContext$AsyncTask;)V
	at org.jboss.as.controller.client.impl.AbstractModelControllerClient$ReadAttachmentInputStreamRequestHandler.handleRequest(AbstractModelControllerClient.java:211)
	at org.jboss.as.protocol.mgmt.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:200)
	at org.jboss.as.protocol.mgmt.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:182)
	at org.jboss.as.protocol.mgmt.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:123)
	at org.jboss.as.protocol.mgmt.ManagementChannelReceiver$1.handleMessage(ManagementChannelReceiver.java:56)
	at org.jboss.as.protocol.mgmt.ManagementChannelReceiver.handleMessage(ManagementChannelReceiver.java:85)
	at org.jboss.remoting3.remote.RemoteConnectionChannel$5.run(RemoteConnectionChannel.java:456)
	at org.jboss.remoting3.EndpointImpl$TrackingExecutor$1.run(EndpointImpl.java:717)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

I am using 
`<dependency>`
            `<groupId>org.wildfly.arquillian</groupId>`
`            <artifactId>wildfly-arquillian-container-embedded</artifactId>`
`            <version>2.0.0.Alpha1</version>`
`            <scope>test</scope>`
`  </dependency>`
dependency for running arquillian tests

**Comment by jamezp** [comment]
Do you have any WildFly dependencies in your pom? It looks like a version mismatch.

**Comment by Afarzin** [comment]
Hi @jamezp 
Thanks for quick reply.

This is our pom dependency configuration:

```
<dependencies>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
        </dependency>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-hibernate5</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.javers</groupId>
            <artifactId>javers-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.javers</groupId>
            <artifactId>javers-hibernate</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.arquillian.junit</groupId>
            <artifactId>arquillian-junit-container</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-arquillian-container-embedded</artifactId>
            <version>8.2.0.Final</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.arquillian.extension</groupId>
            <artifactId>arquillian-transaction-jta</artifactId>
            <version>1.0.1.Final</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.shrinkwrap.resolver</groupId>
            <artifactId>shrinkwrap-resolver-impl-maven</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-embedded</artifactId>
            <version>10.0.0.Alpha6</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-client</artifactId>
            <version>2.19</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-xc</artifactId>
            <version>1.9.13</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-json-provider</artifactId>
            <version>2.6.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>2.8.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.jtds</groupId>
            <artifactId>jtds</artifactId>
            <version>1.3.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <version>3.0.10.Final</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jackson-provider</artifactId>
            <version>3.0.10.Final</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ir.kpp.external.iratco</groupId>
            <artifactId>iraniantourismclub-core-api</artifactId>
            <version>2.0-SNAPSHOT</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ibm.icu</groupId>
            <artifactId>icu4j</artifactId>
        </dependency>
        <dependency>
            <groupId>org.quartz-scheduler</groupId>
            <artifactId>quartz</artifactId>
        </dependency>
        <!--<dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-jaxrs</artifactId>
            <version>1.9.13</version>
            <scope>test</scope>
        </dependency>-->
    </dependencies>
```

This is surefire plugin configuration:
```
<plugin>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.17</version>
    <configuration>
        <forkCount>1</forkCount>
        <reuseForks>true</reuseForks>
        <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <jboss.home>${project.basedir}/target/wildfly-10.0.0.Final</jboss.home>
            <module.path>${env.JBOSS_HOME}/modules</module.path>
        </systemPropertyVariables>
        <redirectTestOutputToFile>false</redirectTestOutputToFile>
        <argLine>-Xmx1024m -XX:MaxPermSize=512m -Dfile.encoding=UTF-8</argLine>
        <environmentVariables>
            <JBOSS_HOME>${project.basedir}/target/wildfly-10.0.0.Final</JBOSS_HOME>
        </environmentVariables>
    </configuration>
</plugin>
```

This is maven-dependency-plugin configuration:
```
<plugin>
    <artifactId>maven-dependency-plugin</artifactId>
    <executions>
        <execution>
            <id>unpack wildfly (jboss)</id>
            <phase>process-test-classes</phase>
            <goals>
                <goal>unpack</goal>
            </goals>
            <configuration>
                <artifactItems>
                    <artifactItem>
                        <groupId>org.wildfly</groupId>
                        <artifactId>wildfly-dist</artifactId>
                        <version>10.0.0.Alpha6</version>
                        <type>zip</type>
                        <overWrite>false</overWrite>
                        <outputDirectory>target</outputDirectory>
                    </artifactItem>
                </artifactItems>
            </configuration>
        </execution>
    </executions>
</plugin>
```

And this is the implementation of deployment method :
```
@Deployment
    @SuppressWarnings("unused") // It's automatically picked by Arquillian
    public static WebArchive createDeployment() {
        File[] files = Maven.resolver().loadPomFromFile("pom.xml")
                .importRuntimeDependencies().resolve().withTransitivity().asFile();
        return ShrinkWrap.create(WebArchive.class)
                .addPackages(true, "")
                /*.addAsResource("moheb.properties")
                .addAsResource(new File("src/test/resources/jndi.properties"), "jndi.properties")
                */
                .addAsResource(new File("target/classes/MessageResources.properties"))
                .addAsResource(new File("target/classes/MessageResources_fa.properties"))
                .addAsResource(new File("target/test-classes/test.properties"))
                .addAsResource(new File("target/classes/club.properties"))
                .addAsResource(new File("target/test-classes/META-INF/persistence.xml"), "META-INF/persistence.xml")
                .addAsLibraries(files)
                .addAsWebInfResource(new File("src/main/webapp/WEB-INF/beans.xml"), "beans.xml")
                .addAsWebInfResource(new File("src/main/webapp/WEB-INF/web.xml"), "web.xml")
                .addAsWebInfResource(new File("target/test-classes/META-INF/tourism-club-ds.xml"), "tourism-club-ds.xml");
    }
```

**Comment by Afarzin** [comment]
I don't know exactly where I am mistaken

**Comment by Afarzin** [comment]
Hey @jamezp ,
You were right, It was a class version mismatch because of this dependency:
```
<dependency>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-embedded</artifactId>
            <version>10.0.0.Alpha6</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by Afarzin** [comment]
Removed it and now I can run tests with Arquillian. Cheers.
